import Providers from './Providers';
import './globals.css'
import { Inter, Pathway_Gothic_One } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const pathwayGothicOne = Pathway_Gothic_One({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={pathwayGothicOne.className}>
      <Providers>
        {children}
      </Providers></body>
    </html>
  )
}
